sample
hinto-janaiyo/monero-bash pull request #2
Opened 2022-05-07 06:59 UTC by natmaka

HI,

This shows which sort of potential problems are detected by shellcheck 

I did not test, please beware

Take care,

2022-05-07 14:14 UTC, hinto-janaiyo commented
Hi, I don't usually use shellcheck but some of these changes are good

Can you merge into `dev` instead of `main`?

2022-05-08 02:43 UTC, natmaka commented
Hi,

You may disable shellcheck's hints which seem useless/bad to you, keeping only those you like.  Given the nature of your code it will be in my opinion better to be very strict.

2022-05-08 16:06 UTC, hinto-janaiyo requested changes
Everything else is good :D

2022-05-08 16:06 UTC, hinto-janai commented on src/func/backup
> + 	if gpg --no-symkey-cache --cipher-algo AES256 -c "backup.tar" ; then
should be `if ! gpg --no-symkey-cache --cipher-algo AES256 -c "backup.tar"; then`

2022-05-08 16:06 UTC, hinto-janai commented on src/func/seed
> +	number=$(printf "%s " "${sha:0:4}")
I think when printing a single regular string `printf "text"` is fine, could you revert these?

2022-05-08 16:06 UTC, hinto-janai commented on src/func/seed
> +local seed
you don't need to initialize and define a variable on separate lines

2022-05-14 05:51 UTC, closed without merging